[package]
name = "quill"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quill-core = {path = "../quill-core"}
ptree = { version = "0.4.0", default-features = false }
