[package]
name    = "reanimate-ui-termion"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reanimate-ui = { path = "../reanimate-ui" }
termion      = "*"
crossbeam    = "*"
ptree        = "*"
